### ISSUE TITLE
iOS  await Devicelocale.currentAsLocale always return 'en' and correct CountryCode

### ISSUE THREAD

**Issue by tdujmic** [magnatronus/flutter-devicelocale#38] opened 2021-11-04 11:34 UTC
Since iOS 15 is launched this issue is presented. Yesterday I saw that only adding array of supported languages into Info.plist 
helps a bit, but for all other languages presented on phone which are not in Info.plist it returns 'en' for language.

I repeat that only happens on iOS 15.x

I added this in Info.plist and my languages are returned correctly now, but any other selected on iPhone returns 'en' if is not in Info.plist again for eg my local language 'hr' is returned as 'en' :

	<key>CFBundleLocalizations</key>
	<array>
		<string>en</string>
		<string>de</string>
		<string>no</string>
		<string>nb</string>
		<string>fr</string>
		<string>da</string>
	</array>

**Comment by josefwilhelm-innio** [comment] 2023-01-23 10:50
I have the same problem, does anyoone have a fix for this?

**Comment by magnatronus** [comment] 2023-01-23 12:16
The answer above from   @tdujmic   (adding the app supported languages into the **Info.plist**) should work.

**Comment by josefwilhelm-innio** [comment] 2023-01-23 13:53
no, it does not work. 

the problem is that the returned locale is wrong if the locale is not in the array. and I want to get the correct device locale even if it's not in the supported locales because I want to show english as fallback. 

with the example above, if I change the language to spanish, the plugin returns 'de' as the currentLocale which is not correct.

**Comment by magnatronus** [comment] 2023-01-23 14:11
> the problem is that the returned locale is wrong if the locale is not in the array. and I want to get the correct device locale even if it's not in the supported locales because I want to show english as fallback.

The plugin was designed to return the locales supported by the app if the app was developed in various languages (i.e. it shows which languages the app has been created for) . 

Can you let me know you default locale (region) set on the phone, The list of preferred languages you have set up  and the content of your info.plist. I will try and replicate and have a look at the issue.

Thanks.

**Comment by josefwilhelm-innio** [comment] 2023-01-23 14:23
ok, then I didn't get that from the description in pub.dev. 

My use case is to get the actual locale of the device in main() to set the locale for the first app start. And I can't use Localizations.of(context) there yet. 

my info.plist 
`	
<key>CFBundleLocalizations</key>
	<array>
		<string>en</string>
		<string>de</string>
		<string>it</string>
	</array>
`

I tried it on an iOS simulator and set the region and language to Spain, 'es_ES', but the plugin shows 'de_ES'.

**Comment by magnatronus** [comment] 2023-02-20 10:49
@josefwilhelm-innio 
A new version has been published(0.6.0) that has new functionality (*defaultLocale*). You should be able to use this in place of **currentLocale** to return the correct default locale settings in iOS (i.e. the first language set and the current region).

**Closed by magnatronus** 2023-02-20 10:49 UTC

**Comment by aytunch** [comment] 2023-03-15 19:47
@magnatronus after this fix do we still need to set `CFBundleLocalizations`? thanks

**Comment by magnatronus** [comment] 2023-03-16 07:56
If you currently use it for anything then yes, the update just gives you the first language and region.
