### ISSUE TITLE
Cannot build, compileSdkVersion 33

### ISSUE THREAD

**Issue by EDnny12** [magnatronus/flutter-devicelocale#46] opened 2022-07-05 15:11 UTC
lambda expressions are not supported in -source 7
    Runnable myRunnable = () -> {
                             ^
  (use -source 8 or higher to enable lambda expressions)
1 error

**Comment by vanlooverenkoen** [comment] 2022-07-06 06:41
Duplicate of #47

**Comment by magnatronus** [comment] 2022-07-06 06:52
Closing - Duplicate of https://github.com/magnatronus/flutter-devicelocale/issues/47

**Closed by magnatronus** 2022-07-06 06:52 UTC
